### ISSUE TITLE
ShowPdfError does not implement std::error::Error

### ISSUE THREAD

**Issue by orlp** [DJDuque/pgfplots#22]
[`ShowPdfError`](https://docs.rs/pgfplots/latest/pgfplots/enum.ShowPdfError.html#) lacks an implementation of the [`Error`](https://doc.rust-lang.org/std/error/trait.Error.html) trait, making it incompatible with libraries such as `anyhow` or even `Box<dyn Error>`.

**Comment by DJDuque** [comment]
Hi, thanks for reporting this.

I have been a bit busy with other stuff lately, and progress on this crate has suffered from this.
I will improve error-handling (most likely with the `thiserror` crate); I have been wanting to do this for a while, and now I have an excuse to make some time for it.

Feel free to ping me if this is not done by the end of the weekend.
